export const jobList = [
  {
    role: "manager",
    companyName: "Asgar Technology Pvt Ltd",
    location: "Bihar, Bettiah, India",
    experience: "0 - 1 year",
    salary: "3 LPA - 10 LPA",
  },
  {
    role: "developer",
    companyName: "TechSpark Solutions",
    location: "Kolkata, India",
    experience: "1 - 3 years",
    salary: "4 LPA - 12 LPA",
  },
  {
    role: "HR Executive",
    companyName: "BlueWave Enterprises",
    location: "Mumbai, Maharashtra, India",
    experience: "2 - 5 years",
    salary: "5 LPA - 15 LPA",
  },
  {
    role: "data analyst",
    companyName: "Infotech Ltd.",
    location: "Bangalore, Karnataka, India",
    experience: "1 - 2 years",
    salary: "6 LPA - 14 LPA",
  },
  {
    role: "web developer",
    companyName: "Tech Innovations",
    location: "Hyderabad, Telangana, India",
    experience: "3 - 5 years",
    salary: "8 LPA - 18 LPA",
  },
  {
    role: "software engineer",
    companyName: "Global Systems",
    location: "Chennai, Tamil Nadu, India",
    experience: "1 - 4 years",
    salary: "5 LPA - 13 LPA",
  },
  {
    role: "UX/UI Designer",
    companyName: "Creative Minds Pvt Ltd",
    location: "Delhi, India",
    experience: "2 - 4 years",
    salary: "6 LPA - 16 LPA",
  },
  {
    role: "marketing executive",
    companyName: "Pioneer Tech",
    location: "Pune, Maharashtra, India",
    experience: "1 - 2 years",
    salary: "4 LPA - 10 LPA",
  },
  {
    role: "network administrator",
    companyName: "TechForce",
    location: "Noida, Uttar Pradesh, India",
    experience: "3 - 6 years",
    salary: "7 LPA - 20 LPA",
  },
  {
    role: "system architect",
    companyName: "TechWorld Ltd.",
    location: "Gurugram, Haryana, India",
    experience: "5 - 8 years",
    salary: "15 LPA - 30 LPA",
  },
  {
    role: "project manager",
    companyName: "FutureTech Solutions",
    location: "Kochi, Kerala, India",
    experience: "4 - 7 years",
    salary: "12 LPA - 25 LPA",
  },
  {
    role: "sales manager",
    companyName: "SalesForce Global",
    location: "Surat, Gujarat, India",
    experience: "2 - 5 years",
    salary: "8 LPA - 18 LPA",
  },
  {
    role: "content writer",
    companyName: "ContentTech Innovations",
    location: "Jaipur, Rajasthan, India",
    experience: "1 - 3 years",
    salary: "3 LPA - 8 LPA",
  },
  {
    role: "graphic designer",
    companyName: "DesignWorks Studio",
    location: "Lucknow, Uttar Pradesh, India",
    experience: "2 - 4 years",
    salary: "4 LPA - 10 LPA",
  },
  {
    role: "database administrator",
    companyName: "Databyte Inc.",
    location: "Mumbai, Maharashtra, India",
    experience: "3 - 6 years",
    salary: "10 LPA - 20 LPA",
  },
  {
    role: "business analyst",
    companyName: "VisionTech Global",
    location: "Delhi, India",
    experience: "2 - 4 years",
    salary: "7 LPA - 15 LPA",
  },
  {
    role: "quality analyst",
    companyName: "QualiSoft Pvt Ltd",
    location: "Chandigarh, India",
    experience: "1 - 2 years",
    salary: "4 LPA - 9 LPA",
  },
  {
    role: "customer support manager",
    companyName: "GlobalTech Solutions",
    location: "Bangalore, Karnataka, India",
    experience: "3 - 6 years",
    salary: "8 LPA - 18 LPA",
  },
  {
    role: "SEO specialist",
    companyName: "SEOMinds Pvt Ltd",
    location: "Ahmedabad, Gujarat, India",
    experience: "1 - 3 years",
    salary: "5 LPA - 10 LPA",
  },
  {
    role: "cloud engineer",
    companyName: "CloudWave Solutions",
    location: "Chennai, Tamil Nadu, India",
    experience: "3 - 5 years",
    salary: "12 LPA - 22 LPA",
  },
  {
    role: "front-end developer",
    companyName: "TechFusion",
    location: "Kolkata, West Bengal, India",
    experience: "2 - 4 years",
    salary: "6 LPA - 14 LPA",
  },
];

export const blog = [
  {
    title: "Top 5 Tips for Job Seekers",
    desc: "Learn how to stand out in the job market with these expert tips.",
    pic: "images/pic1.png",
  },
  {
    title: "How to Ace Your Next Interview",
    desc: "Get ready for your next interview with these proven strategies and tips.",
    pic: "images/pic1.png",
  },
  {
    title: "Crafting the Perfect Resume",
    desc: "Learn how to write a resume that grabs attention and gets you noticed by employers.",
    pic: "images/pic1.png",
  },
  
];

